---
# This role will install redis and apigateway

- name: (re)start redis
  docker_container:
    name: redis
    image: redis
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    ports:
      - "{{ redis.port }}:6379"

- name: git clone apigateway
  git:
    repo: "{{ apigateway.git.repo }}"
    dest: "{{ apigateway.git.dest }}"

- name: build apigateway docker image
  docker_image:
    path: "{{ apigateway.git.dest }}"
    name: apigateway

- name: (re)start apigateway
  docker_container:
    name: apigateway
    image: apigateway
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    hostname: apigateway
    env:
      "REDIS_HOST": "{{ groups['redis'] | first }}"
      "REDIS_PORT": "{{ redis.port }}"
    ports:
      - "{{ apigateway.port.mgmt }}:8080"
      - "{{ apigateway.port.api }}:9000"

- name: wait until the API Gateway in this host is up and running
  uri:
    url: "http://{{ groups['apigateway'] | first }}:{{ apigateway.port.api }}/v1/apis"
  register: result
  until: result.status == 200
  retries: 12
  delay: 5
